### ISSUE TITLE
Add automatic update

### ISSUE THREAD

**Issue by Armand31** [Armand31/Dividoc#9]

**Comment by IzzySoft** [comment]
Oops… Is that automatic update opt-in, and does it properly inform about the implications (e.g. circumventing security measures of the repos people have installed them from)? Otherwise there's a problem as it would violate the [IzzyOnDroid App Inclusion Policy](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion-Policy) (and F-Droid's as well should your app be listed there, @Armand31).

**Comment by IzzySoft** [comment]
No comment, @Armand31? That means we must assume it does not meet the inclusion criteria, and the app has to be removed from IoD.
